name: Main branch and package publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
      CONFIGURATION: Release
      PACKAGES_DIRECTORY: ./packages
      NUGET_SOURCE: https://api.nuget.org/v3/index.json

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/OneBitSoftware.Utilities.OperationResult.sln

    - name: Build
      run: dotnet build ./src/OneBitSoftware.Utilities.OperationResult.sln --no-restore --configuration "${{ env.CONFIGURATION }}"

    - name: Test
      run: dotnet test ./src/OneBitSoftware.Utilities.OperationResult.sln --no-build --verbosity normal

    - name: Pack OneBitSoftware.Utilities.OperationResult
      run: dotnet pack --no-build --configuration "${{ env.CONFIGURATION }}" ./src/OneBitSoftware.Utilities.OperationResult/OneBitSoftware.Utilities.OperationResult.csproj -o "${{ env.PACKAGES_DIRECTORY }}"

    - name: Publish all packages
      run: dotnet nuget push "${{ env.PACKAGES_DIRECTORY }}/*.nupkg" --source "${{ env.NUGET_SOURCE }}" --api-key "${{ env.NUGET_KEY }}" --skip-duplicate